### ISSUE TITLE
Import failure with Python 3.10 and LangChain 0.0.132

### ISSUE THREAD

**Issue by varunnair18** [yasyf/compress-gpt#2]
Hello, I am using compress GPT on Python 3.10.10, LangChain 0.0.132 and I am unable to make it past the import step due to the following error.

Import:
`from compress_gpt.langchain import CompressPrompt as PromptTemplate`

Error:
`OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)`

Any help would be appreciated, thanks!

**Comment by yasyf** [comment]
@varunnair18 let me look into this!

**Comment by yasyf** [comment]
@varunnair18 should be fixed in `0.1.2`!

**Comment by varunnair18** [comment]
It works now, thanks!
